environments:
- aws_access_key: AWS Access Key
  aws_secret_key: AWS Secret Key
  azure_cli_application_id: azure app id
  azure_cli_application_key: azure app key
  azure_cli_tenant_id: azure tenant id
  azure_iot_group: azure iot resource group
  azure_iot_hub_name: azure iot hub name
  base_ova_name: xenial-server-cloudimg-amd64.ova
  base_ova_name_arm: xenial-server-cloudimg-arm64.ova
  binary_webserver: http://192.168.120.40
  contact: Gray Eye
  defaultgateway: '10.13.12.1 '
  deployCustom: false
  deployUniform: true
  dnsdomain: corp.local.io
  dnsserver: 10.13.12.2
  ftNoDown: false
  ftStandard: true
  git_key: 0&^%&$675*&%^&*^$^&*58
  greengrass_device_count: gg iot group
  greengrass_device_stub: Device Stub
  greengrass_s3_bucket: S3 Bucket
  id: '123'
  location: Area 51
  name: Deploy West
  netmask: 255.255.255.0
  ntpservers: 10.13.12.2
  ovftool_image: VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle
  skyway_edge_vm_basename: edgevm
  skyway_edge_vm_network: VM-RegionA01-vDS-COMP
  skyway_edge_vm_password: skyway-passZ!
  skyway_edge_vm_ssh_priv_key: MIIEpAIBAAKCAQE
  skyway_edge_vm_ssh_pub_key: " ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCX/adFOoYeKAcD81EogrCj5/2FsmJD2i/5geS\n\
    \  eGvQZkPmpz54ro5xem6hu4kZaqG3Ej5HGdvZkcNRCK8bTcoRtqHS+uNxfBVAXwgf9G9De8A2wi+\n\
    \  R8iugGbTyIEthHcgC4DruE9oGLry8U3NjWwIy0VUDR7xKkjYRe7HAr/UdXI3FYl59KGtOJdbOzI\n\
    \  XoNQsY9OTgXgTaKCcFoI0y11MQrbqK+twcjz3ItyhecI8xxwHBcZnAomUFIuS8BeFaiUAj7HtMm\n\
    \  Fpc3+plSOiODPI8rPhm5pBiq5FiVrLfjEaBx/1frXuMQ3eaQaQiWzfW8PDVVhnK7650tDg9yjx+\n\
    \  bIFop nobody@this-is-a-placeholder-key.com"
  skyway_edge_vm_user: edgevm
  typeAzure: true
  typeGG: true
  vcenters:
  - clusters:
    - edges:
      - edge_group: Edge One
        id: '9900'
      - edge_group: Edge Two
        id: '777'
      id: 432
      typeAzure: false
      typeGG: true
      vcenter_cluster: Management Cluster
      vcenter_datacenter: West DC
      vcenter_datastore: Tier 1
      vcenter_insecure: true
      vcenter_rp: Mgmt RP
    - edges:
      - edge_group: Edge 1
        id: '9903620'
      - edge_group: Edge 2
        id: '3322'
      id: 221
      typeAzure: false
      typeGG: true
      vcenter_cluster: Workload Cluster
      vcenter_datacenter: West DC
      vcenter_datastore: Tier 2
      vcenter_insecure: true
      vcenter_rp: Workload RP
    - edges:
      - edge_group: New South Edge
        id: '-1098697968'
        typeAzure: true
        typeGG: true
      - edge_group: North Edge
        id: '-1509867464'
        typeAzure: true
        typeGG: true
      id: '930423399'
      vcenter_cluster: South Cluster
      vcenter_datacenter: Retail DC
      vcenter_datastore: NFS Fast
      vcenter_insecure: true
      vcenter_rp: Inflate
    host: vcenter-01.lab.local
    id: 8797
    name: vCenter UAT
    password: VMware1!
    user: administrator@vsphere.local
  - clusters:
    - edges:
      - edge_group: test edge
        id: '-1238752117'
        typeAzure: true
        typeGG: true
      id: '-1008849812'
      vcenter_cluster: Test Cluster
      vcenter_datacenter: TEst DC
      vcenter_datastore: TEst DS
      vcenter_insecure: true
      vcenter_rp: TEst RP
    host: vcenter-01.corp.com
    id: 24553
    name: vCenter Prod
    password: VMware1!
    user: administrator@vsphere.local
